/**
 * Typed access to the manifest `config` block (import config from "mc/config").
 * Wi-Fi is auto-connected by the Moddable net host before main runs; the rest is
 * app config. Override on the mcconfig command line (e.g. deviceSerial="...").
 */

// @ts-expect-error - "mc/config" is generated by the Moddable build from manifest.config
import config from "mc/config";

export type Zone = "left" | "right";

export const WIFI = {
  ssid: config.ssid as string,
  password: config.password as string,
};

export const ORION = config.orion as {
  mcpUrl: string;
  scope: string;
  clientName: string;
  mdnsName: string;
  oauthPort: number;
  deviceSerial: string;
  zone: Zone;
  label: string;
  tempMinF: number;
  tempMaxF: number;
  tempStepF: number;
};

export const TOUCH = config.touch as {
  sda: number;
  scl: number;
  int: number;
  rst: number;
  hz: number;
};

export const ENCODER = config.encoder as { phaseA: number; phaseB: number };
